/**
 * Utility functions for sanitizing, repairing, and safely merging Mermaid.js flowcharts.
 */

function cleanLabel(label: string): string {
  let clean = label.trim().replace(/^["']+|["']+$/g, '').trim();

  // If unmatched trailing parentheses e.g. "Charging (LED indicators))" -> "Charging (LED indicators)"
  const openParen = (clean.match(/\(/g) || []).length;
  const closeParen = (clean.match(/\)/g) || []).length;
  if (closeParen > openParen) {
    clean = clean.replace(/\)+$/, (match) => match.slice(0, openParen - closeParen));
  }

  // Escape any internal double quotes to prevent syntax breakage
  clean = clean.replace(/"/g, "'");
  return `"${clean}"`;
}

/**
 * Sanitizes and repairs raw Mermaid syntax generated by LLMs:
 * - Wraps all node labels in double quotes (supporting emojis, parentheses, colons, slashes).
 * - Fixes prompt typos like C[Label])) -> C["Label"].
 * - Removes invalid markdown fences.
 * - Ensures graph TD header exists.
 */
export function sanitizeMermaid(raw: string): string {
  if (!raw || typeof raw !== 'string') return '';
  const lines = raw.split('\n');
  const cleaned: string[] = [];

  for (let line of lines) {
    let l = line.trim();
    if (!l) continue;
    if (l.startsWith('```')) continue;

    // Fix prompt typo: C[Label])) -> C[Label] (only if not preceded by ()
    l = l.replace(/([^\(\[])\[([^\]]+)\]\)+/g, '$1[$2]');

    // 1. Cylinder: A[( ... )] -> A[("...")]
    l = l.replace(/(\b[a-zA-Z0-9_]+)\s*\[\(\s*(.*?)\s*\)\]/g, (m: string, id: string, label: string) => {
      return `${id}[(${cleanLabel(label)})]`;
    });

    // 2. Stadium: A([ ... ]) -> A(["..."])
    l = l.replace(/(\b[a-zA-Z0-9_]+)\s*\(\[\s*(.*?)\s*\]\)/g, (m: string, id: string, label: string) => {
      return `${id}([${cleanLabel(label)}])`;
    });

    // 3. Circle: A(( ... )) -> A(("..."))
    l = l.replace(/(\b[a-zA-Z0-9_]+)\s*\(\(\s*(.*?)\s*\)\)/g, (m: string, id: string, label: string) => {
      return `${id}((${cleanLabel(label)}))`;
    });

    // 4. Diamond: A{ ... } -> A{"..."}
    l = l.replace(/(\b[a-zA-Z0-9_]+)\s*\{\s*(.*?)\s*\}/g, (m: string, id: string, label: string) => {
      return `${id}{${cleanLabel(label)}}`;
    });

    // 5. Standard Rectangle: A[ ... ] -> A["..."] (excluding cylinder/stadium already processed)
    l = l.replace(/(\b[a-zA-Z0-9_]+)\s*\[\s*(.*?)\s*\](?!\))/g, (m: string, id: string, label: string) => {
      if (label.startsWith('(') && label.endsWith(')')) return m;
      return `${id}[${cleanLabel(label)}]`;
    });

    // Ensure semicolon on classDef
    if (l.startsWith('classDef') && !l.endsWith(';')) {
      l += ';';
    }

    cleaned.push('    ' + l);
  }

  let result = cleaned.join('\n');
  if (!result.includes('graph TD') && !result.includes('flowchart TD')) {
    result = 'graph TD\n' + result;
  }
  return result;
}

/**
 * Safely merges multiple Mermaid flowchart strings under a single Root node.
 * Uses exact structural matching to prevent duplicate prefixing (e.g. c0_c0_A).
 */
export function mergeMermaidFlowcharts(charts: string[], title: string): string {
  if (!charts || charts.length === 0) return '';
  if (charts.length === 1) return sanitizeMermaid(charts[0]);

  const classDefs = new Set<string>();
  classDefs.add('classDef center fill:#fafaf9,stroke:#1c1917,stroke-width:2px;');
  classDefs.add('classDef branch fill:#eff6ff,stroke:#2563eb,stroke-width:1px;');
  classDefs.add('classDef subbranch fill:#f0fdf4,stroke:#16a34a,stroke-width:1px;');
  classDefs.add('classDef research fill:#fff7ed,stroke:#ea580c,stroke-width:1px;');

  let combinedNodes = '';
  let combinedStyles = '';
  const mainChunkStartNodes: string[] = [];

  charts.forEach((chart, index) => {
    const prefix = `c${index}_`;
    const lines = chart.split('\n');

    // 1. Identify real structural node IDs in this chart
    const nodeIds = new Set<string>();
    lines.forEach(line => {
      const t = line.trim();
      if (!t || t.startsWith('graph ') || t.startsWith('flowchart ') || t.startsWith('classDef ') || t.startsWith('class ') || t.startsWith('click ')) return;

      const startMatch = t.match(/^([a-zA-Z0-9_]+)\s*(?:\[|\(|\{|\>|\s*--)/);
      if (startMatch && !['subgraph', 'end', 'graph', 'flowchart'].includes(startMatch[1])) {
        nodeIds.add(startMatch[1]);
      }

      const targetMatches = t.matchAll(/(?:-->|--\s*"[^"]*"\s*-->)\s*([a-zA-Z0-9_]+)/g);
      for (const tm of targetMatches) {
        nodeIds.add(tm[1]);
      }
    });

    let firstNode = '';

    lines.forEach(line => {
      let t = line.trim();
      if (!t || t.startsWith('graph ') || t.startsWith('flowchart ') || t.startsWith('classDef ')) return;

      // Prefix node at start of line
      t = t.replace(/^([a-zA-Z0-9_]+)(\s*(?:\[|\(|\{|\>|\s*--))/, (m: string, id: string, rest: string) => {
        if (nodeIds.has(id)) {
          return `${prefix}${id}${rest}`;
        }
        return m;
      });

      // Prefix node after arrow
      t = t.replace(/((?:-->|--\s*"[^"]*"\s*-->)\s*)([a-zA-Z0-9_]+)/g, (m: string, arrow: string, id: string) => {
        if (nodeIds.has(id)) {
          return `${arrow}${prefix}${id}`;
        }
        return m;
      });

      // Prefix in class statements
      if (t.startsWith('class ')) {
        t = t.replace(/^class\s+([^;]+?)\s+([a-zA-Z0-9_]+);?$/, (m: string, nodes: string, cls: string) => {
          const pref = nodes.split(',').map((n: string) => {
            const trimmed = n.trim();
            return nodeIds.has(trimmed) ? `${prefix}${trimmed}` : trimmed;
          }).join(',');
          return `class ${pref} ${cls};`;
        });
      }

      // Prefix in click statements
      if (t.startsWith('click ')) {
        t = t.replace(/^click\s+([a-zA-Z0-9_]+)/, (m: string, id: string) => {
          return `click ${prefix}${id}`;
        });
      }

      // Track first node for root link
      if (!firstNode) {
        const startMatch = t.match(/^([a-zA-Z0-9_]+)/);
        if (startMatch && !startMatch[1].startsWith('class') && !startMatch[1].startsWith('click')) {
          firstNode = startMatch[1];
          mainChunkStartNodes.push(firstNode);
        }
      }

      if (t.startsWith('class ') || t.startsWith('click ')) {
        combinedStyles += '    ' + t + '\n';
      } else {
        combinedNodes += '    ' + t + '\n';
      }
    });
  });

  let merged = 'graph TD\n';
  classDefs.forEach(def => merged += '    ' + def + '\n');
  merged += '\n';

  const cleanTitle = (title || 'Study Guide').replace(/[\[\]\(\)\{\}"']/g, '');
  merged += `    Root(["🎯 ${cleanTitle}"])\n`;
  merged += `    class Root center;\n`;

  mainChunkStartNodes.forEach((node, idx) => {
    merged += `    Root -- "Part ${idx + 1}" --> ${node}\n`;
  });

  merged += '\n' + combinedNodes + combinedStyles;
  return sanitizeMermaid(merged);
}

/**
 * Generates a clean, guaranteed-to-render fallback flowchart.
 */
export function createFallbackMermaid(title: string): string {
  const cleanTitle = (title || 'Study Guide').replace(/[\[\]\(\)\{\}"']/g, '');
  return `graph TD
    classDef center fill:#fafaf9,stroke:#1c1917,stroke-width:2px;
    classDef branch fill:#eff6ff,stroke:#2563eb,stroke-width:1px;
    classDef subbranch fill:#f0fdf4,stroke:#16a34a,stroke-width:1px;

    Root(["🎯 ${cleanTitle}"])
    class Root center;

    B1(["📖 Overview"])
    B2(["💡 Core Concepts"])
    B3(["📝 Key Summary"])
    class B1,B2,B3 branch;

    Root --> B1
    Root --> B2
    Root --> B3

    S1["Key definitions and principles"]
    S2["Practical applications and workflow"]
    S3["Crucial takeaways and review"]
    class S1,S2,S3 subbranch;

    B1 --> S1
    B2 --> S2
    B3 --> S3
`;
}
